FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app \
    HOST=0.0.0.0 \
    PORT=5078 \
    CELERY_WORKER_POOL=prefork \
    CELERY_WORKER_CONCURRENCY=30 \
    CELERY_WORKER_PREFETCH_MULTIPLIER=1 \
    CELERY_TASK_TIME_LIMIT=1200 \
    CELERY_TASK_SOFT_TIME_LIMIT=900 \
    GUNICORN_WORKERS=8 \
    GUNICORN_TIMEOUT=300 \
    GUNICORN_MAX_REQUESTS=500 \
    GUNICORN_MAX_REQUESTS_JITTER=50

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . ./
RUN chmod +x /app/start.sh

EXPOSE 5078

CMD ["/app/start.sh"]
