-- Seed human-readable descriptions for all known API settings
update public.api_settings
set description = case setting_key
  when 'HOST' then '服务启动地址'
  when 'PORT' then '服务启动端口'
  when 'FLASK_DEBUG' then '是否开启调试模式'
  when 'UPLOAD_MAX_BYTES' then '上传请求最大字节数'
  when 'UPLOAD_MAX_FILE_BYTES' then '单文件上传最大字节数'
  when 'GENERATED_SUITE_RETENTION_DAYS' then '生成结果保留天数'
  when 'GENERATED_SUITE_RETENTION_COUNT' then '生成结果保留数量上限'
  when 'MODE2_ALLOWED_IMAGE_HOSTS' then '允许远程参考图片的域名白名单'
  when 'OPENAI_API_KEY' then 'OpenAI 接口密钥'
  when 'OPENAI_BASE_URL' then 'OpenAI 接口地址'
  when 'OPENAI_MODEL' then 'OpenAI 聊天模型'
  when 'ARK_API_KEY' then 'ARK 接口密钥'
  when 'ARK_BASE_URL' then 'ARK 接口地址'
  when 'ARK_IMAGE_MODEL' then 'ARK 生图模型'
  when 'ARK_IMAGE_SIZE' then 'ARK 生图默认尺寸'
  when 'ARK_IMAGE_QUALITY' then 'ARK 生图质量参数'
  when 'ARK_IMAGE_WATERMARK' then 'ARK 生图是否加水印'
  when 'ARK_SEQUENTIAL_IMAGE_GENERATION' then 'ARK 生图顺序生成模式'
  when 'ARK_SEQUENTIAL_MAX_IMAGES' then 'ARK 顺序生图最大张数'
  when 'MODE2_OPENAI_API_KEY' then 'MODE2 接口密钥'
  when 'MODE2_OPENAI_BASE_URL' then 'MODE2 接口地址'
  when 'MODE2_IMAGE_EDIT_MODEL' then 'MODE2 修图模型'
  when 'MODE2_TEXT2IMAGE_MODEL' then 'MODE2 文生图模型'
  when 'MODE2_DEFAULT_RATIO' then 'MODE2 默认画幅比例'
  when 'MODE2_DEFAULT_RESOLUTION' then 'MODE2 默认分辨率'
  when 'MODE2_DEFAULT_SAMPLE_STRENGTH' then 'MODE2 默认参考强度'
  else description end;
