-- Centralized API settings for aiimagenew
create table if not exists public.api_settings (
  id bigint generated by default as identity primary key,
  scope text not null default 'global',
  setting_key text not null,
  setting_value text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint api_settings_scope_key_unique unique (scope, setting_key)
);

create index if not exists api_settings_scope_idx on public.api_settings (scope);

create or replace function public.set_api_settings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists api_settings_updated_at on public.api_settings;
create trigger api_settings_updated_at
before update on public.api_settings
for each row
execute function public.set_api_settings_updated_at();

alter table public.api_settings enable row level security;

drop policy if exists "api_settings service role full access" on public.api_settings;
create policy "api_settings service role full access"
on public.api_settings
for all
to service_role
using (true)
with check (true);
