-- User points transaction ledger and atomic points mutations
create table if not exists public.user_points_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  amount integer not null,
  balance_before integer not null,
  balance_after integer not null,
  transaction_type text not null,
  reason text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  source text not null default 'api',
  related_transaction_id bigint references public.user_points_transactions (id) on delete set null,
  created_at timestamptz not null default now(),
  constraint user_points_transactions_amount_nonzero check (amount <> 0)
);

create index if not exists user_points_transactions_user_id_created_at_idx
on public.user_points_transactions (user_id, created_at desc);

create index if not exists user_points_transactions_type_idx
on public.user_points_transactions (transaction_type);

alter table public.user_points_transactions enable row level security;

drop policy if exists "user_points_transactions service role full access" on public.user_points_transactions;
create policy "user_points_transactions service role full access"
on public.user_points_transactions
for all
to service_role
using (true)
with check (true);

create or replace function public.insert_user_points_transaction(
  p_user_id uuid,
  p_amount integer,
  p_balance_before integer,
  p_balance_after integer,
  p_transaction_type text,
  p_reason text default '',
  p_metadata jsonb default '{}'::jsonb,
  p_source text default 'api',
  p_related_transaction_id bigint default null
)
returns public.user_points_transactions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.user_points_transactions;
begin
  insert into public.user_points_transactions (
    user_id,
    amount,
    balance_before,
    balance_after,
    transaction_type,
    reason,
    metadata,
    source,
    related_transaction_id
  ) values (
    p_user_id,
    p_amount,
    p_balance_before,
    p_balance_after,
    coalesce(nullif(trim(p_transaction_type), ''), 'unknown'),
    coalesce(p_reason, ''),
    coalesce(p_metadata, '{}'::jsonb),
    coalesce(nullif(trim(p_source), ''), 'api'),
    p_related_transaction_id
  )
  returning * into v_row;

  return v_row;
end;
$$;

create or replace function public.award_signup_bonus_points(p_user_id uuid, p_amount integer)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.user_points_balances;
  v_previous_balance integer;
  v_transaction public.user_points_transactions;
begin
  if p_user_id is null then
    raise exception 'user_id 不能为空';
  end if;
  if p_amount is null or p_amount < 0 then
    raise exception 'amount 不能为空';
  end if;

  perform public.ensure_user_points_balance(p_user_id);

  select balance into v_previous_balance
  from public.user_points_balances
  where user_id = p_user_id;

  update public.user_points_balances
  set balance = balance + p_amount,
      total_earned = total_earned + p_amount,
      signup_bonus_awarded_at = coalesce(signup_bonus_awarded_at, now())
  where user_id = p_user_id
    and signup_bonus_awarded_at is null
  returning * into v_row;

  if found then
    v_transaction := public.insert_user_points_transaction(
      p_user_id,
      p_amount,
      coalesce(v_previous_balance, 0),
      v_row.balance,
      'signup_bonus',
      '新用户注册赠送积分',
      jsonb_build_object('amount', p_amount),
      'system',
      null
    );

    return jsonb_build_object(
      'success', true,
      'awarded', true,
      'balance_row', to_jsonb(v_row),
      'transaction_row', to_jsonb(v_transaction)
    );
  end if;

  select * into v_row
  from public.user_points_balances
  where user_id = p_user_id;

  return jsonb_build_object(
    'success', true,
    'awarded', false,
    'balance_row', to_jsonb(v_row)
  );
end;
$$;

create or replace function public.claim_daily_free_points(p_user_id uuid, p_amount integer)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.user_points_balances;
  v_previous_balance integer;
  v_transaction public.user_points_transactions;
begin
  if p_user_id is null then
    raise exception 'user_id 不能为空';
  end if;
  if p_amount is null or p_amount < 0 then
    raise exception 'amount 不能为空';
  end if;

  perform public.ensure_user_points_balance(p_user_id);

  select balance into v_previous_balance
  from public.user_points_balances
  where user_id = p_user_id;

  update public.user_points_balances
  set balance = balance + p_amount,
      total_earned = total_earned + p_amount,
      last_daily_claim_at = now()
  where user_id = p_user_id
    and (
      last_daily_claim_at is null
      or timezone('UTC', last_daily_claim_at)::date < timezone('UTC', now())::date
    )
  returning * into v_row;

  if found then
    v_transaction := public.insert_user_points_transaction(
      p_user_id,
      p_amount,
      coalesce(v_previous_balance, 0),
      v_row.balance,
      'daily_free',
      '每日免费领取积分',
      jsonb_build_object('amount', p_amount),
      'system',
      null
    );

    return jsonb_build_object(
      'success', true,
      'claimed', true,
      'balance_row', to_jsonb(v_row),
      'transaction_row', to_jsonb(v_transaction)
    );
  end if;

  select * into v_row
  from public.user_points_balances
  where user_id = p_user_id;

  return jsonb_build_object(
    'success', true,
    'claimed', false,
    'reason', 'already_claimed_today',
    'balance_row', to_jsonb(v_row)
  );
end;
$$;

create or replace function public.spend_user_points(
  p_user_id uuid,
  p_amount integer,
  p_transaction_type text default 'consume',
  p_reason text default '',
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.user_points_balances;
  v_previous_balance integer;
  v_transaction public.user_points_transactions;
begin
  if p_user_id is null then
    raise exception 'user_id 不能为空';
  end if;
  if p_amount is null or p_amount < 0 then
    raise exception 'amount 不能为空';
  end if;

  perform public.ensure_user_points_balance(p_user_id);

  select balance into v_previous_balance
  from public.user_points_balances
  where user_id = p_user_id;

  update public.user_points_balances
  set balance = balance - p_amount,
      total_spent = total_spent + p_amount
  where user_id = p_user_id
    and balance >= p_amount
  returning * into v_row;

  if found then
    v_transaction := public.insert_user_points_transaction(
      p_user_id,
      -p_amount,
      coalesce(v_previous_balance, 0),
      v_row.balance,
      coalesce(nullif(trim(p_transaction_type), ''), 'consume'),
      coalesce(p_reason, ''),
      coalesce(p_metadata, '{}'::jsonb),
      'api',
      null
    );

    return jsonb_build_object(
      'success', true,
      'spent', true,
      'balance_row', to_jsonb(v_row),
      'transaction_row', to_jsonb(v_transaction)
    );
  end if;

  raise exception '积分余额不足';
end;
$$;

create or replace function public.add_user_points(
  p_user_id uuid,
  p_amount integer,
  p_transaction_type text default 'refund',
  p_reason text default '',
  p_metadata jsonb default '{}'::jsonb,
  p_related_transaction_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.user_points_balances;
  v_previous_balance integer;
  v_transaction public.user_points_transactions;
begin
  if p_user_id is null then
    raise exception 'user_id 不能为空';
  end if;
  if p_amount is null or p_amount < 0 then
    raise exception 'amount 不能为空';
  end if;

  perform public.ensure_user_points_balance(p_user_id);

  select balance into v_previous_balance
  from public.user_points_balances
  where user_id = p_user_id;

  update public.user_points_balances
  set balance = balance + p_amount,
      total_earned = total_earned + p_amount
  where user_id = p_user_id
  returning * into v_row;

  v_transaction := public.insert_user_points_transaction(
    p_user_id,
    p_amount,
    coalesce(v_previous_balance, 0),
    v_row.balance,
    coalesce(nullif(trim(p_transaction_type), ''), 'refund'),
    coalesce(p_reason, ''),
    coalesce(p_metadata, '{}'::jsonb),
    'api',
    p_related_transaction_id
  );

  return jsonb_build_object(
    'success', true,
    'added', true,
    'balance_row', to_jsonb(v_row),
    'transaction_row', to_jsonb(v_transaction)
  );
end;
$$;
